--- #YAML:1.0
name:               Acme-CPANAuthors-Brazilian
version:            0.09
abstract:           We are brazilian CPAN authors
author:
    - Breno G. de Oliveira <garu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Acme::CPANAuthors:    0
    Test::More:           0.47
    Test::UseAllModules:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
